# Generated by Django 4.2.30 on 2026-05-24 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате 8XXXXXXXXXX или +7XXXXXXXXXX', regex='^(\\+7|8)\\d{10}$')], verbose_name='Телефон'),
        ),
    ]
